#!/bin/bash

# TODO: Modify this file to create a shell script that is able to use awk to go through a file
# formatted like pokemon.dat and provides a printed report in the following format (where your 
# script correctly calculates the values that go into the [VALUE] placeholders):
# ======= SUMMARY OF POKEMON.DAT ======
#    Total Non-Legendary Pokemon: [VALUE]
#    Avg. HP: [VALUE]
#    Avg. Defense: [VALUE]
# ======= END SUMMARY =======

# NOTE THAT YOU MUST USE AWK OR YOU WILL LOSE POINTS
# The "Avg." values should be calculated as mean values for the corresponding columns.
# The averages must only be for non-legendary pokemon.
# The spacing and header formatting should match the above formatting description exactly.
# There should be a comment explaining the purpose of each line in your shell script. 
# The data file will be passed in to the script as a positional parameter and will not
# necessarily be called pokemon.dat. However, you can assume that any file passed to this
# script will be formatted exactly the way pokemon.dat is formatted.

# use tab character as field separator
BEGIN{FS="\t"
#initialize non-legendary count, hp, and defense variables 
count = 0;
hp = 0;
defense = 0}
{

# if the pokemon is not legendary, increment stats to counter variables 
if ($13 == "False"){

# add hp column to counter 
hp += $6;

# add defense column to counter 
defense += $8;

# increment count by 1 
count++; 

		}

} 
END{
# print end messages 
print"======= SUMMARY OF POKEMON.DAT ======"
printf"   Total Non-Legendary Pokemon: %d\n", count
printf"   Avg. HP: %d\n", hp / count
printf"   Avg. Defense: %d\n", defense / count
print"======= END SUMMARY ======="
}



